import type {IconType} from "react-icons";

import {HiAcademicCap} from "react-icons/hi";
import {HiAdjustments} from "react-icons/hi";
import {HiAnnotation} from "react-icons/hi";
import {HiArchive} from "react-icons/hi";
import {HiArrowCircleDown} from "react-icons/hi";
import {HiArrowCircleLeft} from "react-icons/hi";
import {HiArrowCircleRight} from "react-icons/hi";
import {HiArrowCircleUp} from "react-icons/hi";
import {HiArrowDown} from "react-icons/hi";
import {HiArrowLeft} from "react-icons/hi";
import {HiArrowNarrowDown} from "react-icons/hi";
import {HiArrowNarrowLeft} from "react-icons/hi";
import {HiArrowNarrowRight} from "react-icons/hi";
import {HiArrowNarrowUp} from "react-icons/hi";
import {HiArrowRight} from "react-icons/hi";
import {HiArrowSmDown} from "react-icons/hi";
import {HiArrowSmLeft} from "react-icons/hi";
import {HiArrowSmRight} from "react-icons/hi";
import {HiArrowSmUp} from "react-icons/hi";
import {HiArrowUp} from "react-icons/hi";
import {HiArrowsExpand} from "react-icons/hi";
import {HiAtSymbol} from "react-icons/hi";
import {HiBackspace} from "react-icons/hi";
import {HiBadgeCheck} from "react-icons/hi";
import {HiBan} from "react-icons/hi";
import {HiBeaker} from "react-icons/hi";
import {HiBell} from "react-icons/hi";
import {HiBookOpen} from "react-icons/hi";
import {HiBookmarkAlt} from "react-icons/hi";
import {HiBookmark} from "react-icons/hi";
import {HiBriefcase} from "react-icons/hi";
import {HiCake} from "react-icons/hi";
import {HiCalculator} from "react-icons/hi";
import {HiCalendar} from "react-icons/hi";
import {HiCamera} from "react-icons/hi";
import {HiCash} from "react-icons/hi";
import {HiChartBar} from "react-icons/hi";
import {HiChartPie} from "react-icons/hi";
import {HiChartSquareBar} from "react-icons/hi";
import {HiChatAlt2} from "react-icons/hi";
import {HiChatAlt} from "react-icons/hi";
import {HiChat} from "react-icons/hi";
import {HiCheckCircle} from "react-icons/hi";
import {HiCheck} from "react-icons/hi";
import {HiChevronDoubleDown} from "react-icons/hi";
import {HiChevronDoubleLeft} from "react-icons/hi";
import {HiChevronDoubleRight} from "react-icons/hi";
import {HiChevronDoubleUp} from "react-icons/hi";
import {HiChevronDown} from "react-icons/hi";
import {HiChevronLeft} from "react-icons/hi";
import {HiChevronRight} from "react-icons/hi";
import {HiChevronUp} from "react-icons/hi";
import {HiChip} from "react-icons/hi";
import {HiClipboardCheck} from "react-icons/hi";
import {HiClipboardCopy} from "react-icons/hi";
import {HiClipboardList} from "react-icons/hi";
import {HiClipboard} from "react-icons/hi";
import {HiClock} from "react-icons/hi";
import {HiCloudDownload} from "react-icons/hi";
import {HiCloudUpload} from "react-icons/hi";
import {HiCloud} from "react-icons/hi";
import {HiCode} from "react-icons/hi";
import {HiCog} from "react-icons/hi";
import {HiCollection} from "react-icons/hi";
import {HiColorSwatch} from "react-icons/hi";
import {HiCreditCard} from "react-icons/hi";
import {HiCubeTransparent} from "react-icons/hi";
import {HiCube} from "react-icons/hi";
import {HiCurrencyBangladeshi} from "react-icons/hi";
import {HiCurrencyDollar} from "react-icons/hi";
import {HiCurrencyEuro} from "react-icons/hi";
import {HiCurrencyPound} from "react-icons/hi";
import {HiCurrencyRupee} from "react-icons/hi";
import {HiCurrencyYen} from "react-icons/hi";
import {HiCursorClick} from "react-icons/hi";
import {HiDatabase} from "react-icons/hi";
import {HiDesktopComputer} from "react-icons/hi";
import {HiDeviceMobile} from "react-icons/hi";
import {HiDeviceTablet} from "react-icons/hi";
import {HiDocumentAdd} from "react-icons/hi";
import {HiDocumentDownload} from "react-icons/hi";
import {HiDocumentDuplicate} from "react-icons/hi";
import {HiDocumentRemove} from "react-icons/hi";
import {HiDocumentReport} from "react-icons/hi";
import {HiDocumentSearch} from "react-icons/hi";
import {HiDocumentText} from "react-icons/hi";
import {HiDocument} from "react-icons/hi";
import {HiDotsCircleHorizontal} from "react-icons/hi";
import {HiDotsHorizontal} from "react-icons/hi";
import {HiDotsVertical} from "react-icons/hi";
import {HiDownload} from "react-icons/hi";
import {HiDuplicate} from "react-icons/hi";
import {HiEmojiHappy} from "react-icons/hi";
import {HiEmojiSad} from "react-icons/hi";
import {HiExclamationCircle} from "react-icons/hi";
import {HiExclamation} from "react-icons/hi";
import {HiExternalLink} from "react-icons/hi";
import {HiEyeOff} from "react-icons/hi";
import {HiEye} from "react-icons/hi";
import {HiFastForward} from "react-icons/hi";
import {HiFilm} from "react-icons/hi";
import {HiFilter} from "react-icons/hi";
import {HiFingerPrint} from "react-icons/hi";
import {HiFire} from "react-icons/hi";
import {HiFlag} from "react-icons/hi";
import {HiFolderAdd} from "react-icons/hi";
import {HiFolderDownload} from "react-icons/hi";
import {HiFolderOpen} from "react-icons/hi";
import {HiFolderRemove} from "react-icons/hi";
import {HiFolder} from "react-icons/hi";
import {HiGift} from "react-icons/hi";
import {HiGlobeAlt} from "react-icons/hi";
import {HiGlobe} from "react-icons/hi";
import {HiHand} from "react-icons/hi";
import {HiHashtag} from "react-icons/hi";
import {HiHeart} from "react-icons/hi";
import {HiHome} from "react-icons/hi";
import {HiIdentification} from "react-icons/hi";
import {HiInboxIn} from "react-icons/hi";
import {HiInbox} from "react-icons/hi";
import {HiInformationCircle} from "react-icons/hi";
import {HiKey} from "react-icons/hi";
import {HiLibrary} from "react-icons/hi";
import {HiLightBulb} from "react-icons/hi";
import {HiLightningBolt} from "react-icons/hi";
import {HiLink} from "react-icons/hi";
import {HiLocationMarker} from "react-icons/hi";
import {HiLockClosed} from "react-icons/hi";
import {HiLockOpen} from "react-icons/hi";
import {HiLogin} from "react-icons/hi";
import {HiLogout} from "react-icons/hi";
import {HiMailOpen} from "react-icons/hi";
import {HiMail} from "react-icons/hi";
import {HiMap} from "react-icons/hi";
import {HiMenuAlt1} from "react-icons/hi";
import {HiMenuAlt2} from "react-icons/hi";
import {HiMenuAlt3} from "react-icons/hi";
import {HiMenuAlt4} from "react-icons/hi";
import {HiMenu} from "react-icons/hi";
import {HiMicrophone} from "react-icons/hi";
import {HiMinusCircle} from "react-icons/hi";
import {HiMinusSm} from "react-icons/hi";
import {HiMinus} from "react-icons/hi";
import {HiMoon} from "react-icons/hi";
import {HiMusicNote} from "react-icons/hi";
import {HiNewspaper} from "react-icons/hi";
import {HiOfficeBuilding} from "react-icons/hi";
import {HiPaperAirplane} from "react-icons/hi";
import {HiPaperClip} from "react-icons/hi";
import {HiPause} from "react-icons/hi";
import {HiPencilAlt} from "react-icons/hi";
import {HiPencil} from "react-icons/hi";
import {HiPhoneIncoming} from "react-icons/hi";
import {HiPhoneMissedCall} from "react-icons/hi";
import {HiPhoneOutgoing} from "react-icons/hi";
import {HiPhone} from "react-icons/hi";
import {HiPhotograph} from "react-icons/hi";
import {HiPlay} from "react-icons/hi";
import {HiPlusCircle} from "react-icons/hi";
import {HiPlusSm} from "react-icons/hi";
import {HiPlus} from "react-icons/hi";
import {HiPresentationChartBar} from "react-icons/hi";
import {HiPresentationChartLine} from "react-icons/hi";
import {HiPrinter} from "react-icons/hi";
import {HiPuzzle} from "react-icons/hi";
import {HiQrcode} from "react-icons/hi";
import {HiQuestionMarkCircle} from "react-icons/hi";
import {HiReceiptRefund} from "react-icons/hi";
import {HiReceiptTax} from "react-icons/hi";
import {HiRefresh} from "react-icons/hi";
import {HiReply} from "react-icons/hi";
import {HiRewind} from "react-icons/hi";
import {HiRss} from "react-icons/hi";
import {HiSaveAs} from "react-icons/hi";
import {HiSave} from "react-icons/hi";
import {HiScale} from "react-icons/hi";
import {HiScissors} from "react-icons/hi";
import {HiSearchCircle} from "react-icons/hi";
import {HiSearch} from "react-icons/hi";
import {HiSelector} from "react-icons/hi";
import {HiServer} from "react-icons/hi";
import {HiShare} from "react-icons/hi";
import {HiShieldCheck} from "react-icons/hi";
import {HiShieldExclamation} from "react-icons/hi";
import {HiShoppingBag} from "react-icons/hi";
import {HiShoppingCart} from "react-icons/hi";
import {HiSortAscending} from "react-icons/hi";
import {HiSortDescending} from "react-icons/hi";
import {HiSparkles} from "react-icons/hi";
import {HiSpeakerphone} from "react-icons/hi";
import {HiStar} from "react-icons/hi";
import {HiStatusOffline} from "react-icons/hi";
import {HiStatusOnline} from "react-icons/hi";
import {HiStop} from "react-icons/hi";
import {HiSun} from "react-icons/hi";
import {HiSupport} from "react-icons/hi";
import {HiSwitchHorizontal} from "react-icons/hi";
import {HiSwitchVertical} from "react-icons/hi";
import {HiTable} from "react-icons/hi";
import {HiTag} from "react-icons/hi";
import {HiTemplate} from "react-icons/hi";
import {HiTerminal} from "react-icons/hi";
import {HiThumbDown} from "react-icons/hi";
import {HiThumbUp} from "react-icons/hi";
import {HiTicket} from "react-icons/hi";
import {HiTranslate} from "react-icons/hi";
import {HiTrash} from "react-icons/hi";
import {HiTrendingDown} from "react-icons/hi";
import {HiTrendingUp} from "react-icons/hi";
import {HiTruck} from "react-icons/hi";
import {HiUpload} from "react-icons/hi";
import {HiUserAdd} from "react-icons/hi";
import {HiUserCircle} from "react-icons/hi";
import {HiUserGroup} from "react-icons/hi";
import {HiUserRemove} from "react-icons/hi";
import {HiUser} from "react-icons/hi";
import {HiUsers} from "react-icons/hi";
import {HiVariable} from "react-icons/hi";
import {HiVideoCamera} from "react-icons/hi";
import {HiViewBoards} from "react-icons/hi";
import {HiViewGridAdd} from "react-icons/hi";
import {HiViewGrid} from "react-icons/hi";
import {HiViewList} from "react-icons/hi";
import {HiVolumeOff} from "react-icons/hi";
import {HiVolumeUp} from "react-icons/hi";
import {HiWifi} from "react-icons/hi";
import {HiXCircle} from "react-icons/hi";
import {HiX} from "react-icons/hi";
import {HiZoomIn} from "react-icons/hi";
import {HiZoomOut} from "react-icons/hi";
import {HiOutlineAcademicCap} from "react-icons/hi";
import {HiOutlineAdjustments} from "react-icons/hi";
import {HiOutlineAnnotation} from "react-icons/hi";
import {HiOutlineArchive} from "react-icons/hi";
import {HiOutlineArrowCircleDown} from "react-icons/hi";
import {HiOutlineArrowCircleLeft} from "react-icons/hi";
import {HiOutlineArrowCircleRight} from "react-icons/hi";
import {HiOutlineArrowCircleUp} from "react-icons/hi";
import {HiOutlineArrowDown} from "react-icons/hi";
import {HiOutlineArrowLeft} from "react-icons/hi";
import {HiOutlineArrowNarrowDown} from "react-icons/hi";
import {HiOutlineArrowNarrowLeft} from "react-icons/hi";
import {HiOutlineArrowNarrowRight} from "react-icons/hi";
import {HiOutlineArrowNarrowUp} from "react-icons/hi";
import {HiOutlineArrowRight} from "react-icons/hi";
import {HiOutlineArrowSmDown} from "react-icons/hi";
import {HiOutlineArrowSmLeft} from "react-icons/hi";
import {HiOutlineArrowSmRight} from "react-icons/hi";
import {HiOutlineArrowSmUp} from "react-icons/hi";
import {HiOutlineArrowUp} from "react-icons/hi";
import {HiOutlineArrowsExpand} from "react-icons/hi";
import {HiOutlineAtSymbol} from "react-icons/hi";
import {HiOutlineBackspace} from "react-icons/hi";
import {HiOutlineBadgeCheck} from "react-icons/hi";
import {HiOutlineBan} from "react-icons/hi";
import {HiOutlineBeaker} from "react-icons/hi";
import {HiOutlineBell} from "react-icons/hi";
import {HiOutlineBookOpen} from "react-icons/hi";
import {HiOutlineBookmarkAlt} from "react-icons/hi";
import {HiOutlineBookmark} from "react-icons/hi";
import {HiOutlineBriefcase} from "react-icons/hi";
import {HiOutlineCake} from "react-icons/hi";
import {HiOutlineCalculator} from "react-icons/hi";
import {HiOutlineCalendar} from "react-icons/hi";
import {HiOutlineCamera} from "react-icons/hi";
import {HiOutlineCash} from "react-icons/hi";
import {HiOutlineChartBar} from "react-icons/hi";
import {HiOutlineChartPie} from "react-icons/hi";
import {HiOutlineChartSquareBar} from "react-icons/hi";
import {HiOutlineChatAlt2} from "react-icons/hi";
import {HiOutlineChatAlt} from "react-icons/hi";
import {HiOutlineChat} from "react-icons/hi";
import {HiOutlineCheckCircle} from "react-icons/hi";
import {HiOutlineCheck} from "react-icons/hi";
import {HiOutlineChevronDoubleDown} from "react-icons/hi";
import {HiOutlineChevronDoubleLeft} from "react-icons/hi";
import {HiOutlineChevronDoubleRight} from "react-icons/hi";
import {HiOutlineChevronDoubleUp} from "react-icons/hi";
import {HiOutlineChevronDown} from "react-icons/hi";
import {HiOutlineChevronLeft} from "react-icons/hi";
import {HiOutlineChevronRight} from "react-icons/hi";
import {HiOutlineChevronUp} from "react-icons/hi";
import {HiOutlineChip} from "react-icons/hi";
import {HiOutlineClipboardCheck} from "react-icons/hi";
import {HiOutlineClipboardCopy} from "react-icons/hi";
import {HiOutlineClipboardList} from "react-icons/hi";
import {HiOutlineClipboard} from "react-icons/hi";
import {HiOutlineClock} from "react-icons/hi";
import {HiOutlineCloudDownload} from "react-icons/hi";
import {HiOutlineCloudUpload} from "react-icons/hi";
import {HiOutlineCloud} from "react-icons/hi";
import {HiOutlineCode} from "react-icons/hi";
import {HiOutlineCog} from "react-icons/hi";
import {HiOutlineCollection} from "react-icons/hi";
import {HiOutlineColorSwatch} from "react-icons/hi";
import {HiOutlineCreditCard} from "react-icons/hi";
import {HiOutlineCubeTransparent} from "react-icons/hi";
import {HiOutlineCube} from "react-icons/hi";
import {HiOutlineCurrencyBangladeshi} from "react-icons/hi";
import {HiOutlineCurrencyDollar} from "react-icons/hi";
import {HiOutlineCurrencyEuro} from "react-icons/hi";
import {HiOutlineCurrencyPound} from "react-icons/hi";
import {HiOutlineCurrencyRupee} from "react-icons/hi";
import {HiOutlineCurrencyYen} from "react-icons/hi";
import {HiOutlineCursorClick} from "react-icons/hi";
import {HiOutlineDatabase} from "react-icons/hi";
import {HiOutlineDesktopComputer} from "react-icons/hi";
import {HiOutlineDeviceMobile} from "react-icons/hi";
import {HiOutlineDeviceTablet} from "react-icons/hi";
import {HiOutlineDocumentAdd} from "react-icons/hi";
import {HiOutlineDocumentDownload} from "react-icons/hi";
import {HiOutlineDocumentDuplicate} from "react-icons/hi";
import {HiOutlineDocumentRemove} from "react-icons/hi";
import {HiOutlineDocumentReport} from "react-icons/hi";
import {HiOutlineDocumentSearch} from "react-icons/hi";
import {HiOutlineDocumentText} from "react-icons/hi";
import {HiOutlineDocument} from "react-icons/hi";
import {HiOutlineDotsCircleHorizontal} from "react-icons/hi";
import {HiOutlineDotsHorizontal} from "react-icons/hi";
import {HiOutlineDotsVertical} from "react-icons/hi";
import {HiOutlineDownload} from "react-icons/hi";
import {HiOutlineDuplicate} from "react-icons/hi";
import {HiOutlineEmojiHappy} from "react-icons/hi";
import {HiOutlineEmojiSad} from "react-icons/hi";
import {HiOutlineExclamationCircle} from "react-icons/hi";
import {HiOutlineExclamation} from "react-icons/hi";
import {HiOutlineExternalLink} from "react-icons/hi";
import {HiOutlineEyeOff} from "react-icons/hi";
import {HiOutlineEye} from "react-icons/hi";
import {HiOutlineFastForward} from "react-icons/hi";
import {HiOutlineFilm} from "react-icons/hi";
import {HiOutlineFilter} from "react-icons/hi";
import {HiOutlineFingerPrint} from "react-icons/hi";
import {HiOutlineFire} from "react-icons/hi";
import {HiOutlineFlag} from "react-icons/hi";
import {HiOutlineFolderAdd} from "react-icons/hi";
import {HiOutlineFolderDownload} from "react-icons/hi";
import {HiOutlineFolderOpen} from "react-icons/hi";
import {HiOutlineFolderRemove} from "react-icons/hi";
import {HiOutlineFolder} from "react-icons/hi";
import {HiOutlineGift} from "react-icons/hi";
import {HiOutlineGlobeAlt} from "react-icons/hi";
import {HiOutlineGlobe} from "react-icons/hi";
import {HiOutlineHand} from "react-icons/hi";
import {HiOutlineHashtag} from "react-icons/hi";
import {HiOutlineHeart} from "react-icons/hi";
import {HiOutlineHome} from "react-icons/hi";
import {HiOutlineIdentification} from "react-icons/hi";
import {HiOutlineInboxIn} from "react-icons/hi";
import {HiOutlineInbox} from "react-icons/hi";
import {HiOutlineInformationCircle} from "react-icons/hi";
import {HiOutlineKey} from "react-icons/hi";
import {HiOutlineLibrary} from "react-icons/hi";
import {HiOutlineLightBulb} from "react-icons/hi";
import {HiOutlineLightningBolt} from "react-icons/hi";
import {HiOutlineLink} from "react-icons/hi";
import {HiOutlineLocationMarker} from "react-icons/hi";
import {HiOutlineLockClosed} from "react-icons/hi";
import {HiOutlineLockOpen} from "react-icons/hi";
import {HiOutlineLogin} from "react-icons/hi";
import {HiOutlineLogout} from "react-icons/hi";
import {HiOutlineMailOpen} from "react-icons/hi";
import {HiOutlineMail} from "react-icons/hi";
import {HiOutlineMap} from "react-icons/hi";
import {HiOutlineMenuAlt1} from "react-icons/hi";
import {HiOutlineMenuAlt2} from "react-icons/hi";
import {HiOutlineMenuAlt3} from "react-icons/hi";
import {HiOutlineMenuAlt4} from "react-icons/hi";
import {HiOutlineMenu} from "react-icons/hi";
import {HiOutlineMicrophone} from "react-icons/hi";
import {HiOutlineMinusCircle} from "react-icons/hi";
import {HiOutlineMinusSm} from "react-icons/hi";
import {HiOutlineMinus} from "react-icons/hi";
import {HiOutlineMoon} from "react-icons/hi";
import {HiOutlineMusicNote} from "react-icons/hi";
import {HiOutlineNewspaper} from "react-icons/hi";
import {HiOutlineOfficeBuilding} from "react-icons/hi";
import {HiOutlinePaperAirplane} from "react-icons/hi";
import {HiOutlinePaperClip} from "react-icons/hi";
import {HiOutlinePause} from "react-icons/hi";
import {HiOutlinePencilAlt} from "react-icons/hi";
import {HiOutlinePencil} from "react-icons/hi";
import {HiOutlinePhoneIncoming} from "react-icons/hi";
import {HiOutlinePhoneMissedCall} from "react-icons/hi";
import {HiOutlinePhoneOutgoing} from "react-icons/hi";
import {HiOutlinePhone} from "react-icons/hi";
import {HiOutlinePhotograph} from "react-icons/hi";
import {HiOutlinePlay} from "react-icons/hi";
import {HiOutlinePlusCircle} from "react-icons/hi";
import {HiOutlinePlusSm} from "react-icons/hi";
import {HiOutlinePlus} from "react-icons/hi";
import {HiOutlinePresentationChartBar} from "react-icons/hi";
import {HiOutlinePresentationChartLine} from "react-icons/hi";
import {HiOutlinePrinter} from "react-icons/hi";
import {HiOutlinePuzzle} from "react-icons/hi";
import {HiOutlineQrcode} from "react-icons/hi";
import {HiOutlineQuestionMarkCircle} from "react-icons/hi";
import {HiOutlineReceiptRefund} from "react-icons/hi";
import {HiOutlineReceiptTax} from "react-icons/hi";
import {HiOutlineRefresh} from "react-icons/hi";
import {HiOutlineReply} from "react-icons/hi";
import {HiOutlineRewind} from "react-icons/hi";
import {HiOutlineRss} from "react-icons/hi";
import {HiOutlineSaveAs} from "react-icons/hi";
import {HiOutlineSave} from "react-icons/hi";
import {HiOutlineScale} from "react-icons/hi";
import {HiOutlineScissors} from "react-icons/hi";
import {HiOutlineSearchCircle} from "react-icons/hi";
import {HiOutlineSearch} from "react-icons/hi";
import {HiOutlineSelector} from "react-icons/hi";
import {HiOutlineServer} from "react-icons/hi";
import {HiOutlineShare} from "react-icons/hi";
import {HiOutlineShieldCheck} from "react-icons/hi";
import {HiOutlineShieldExclamation} from "react-icons/hi";
import {HiOutlineShoppingBag} from "react-icons/hi";
import {HiOutlineShoppingCart} from "react-icons/hi";
import {HiOutlineSortAscending} from "react-icons/hi";
import {HiOutlineSortDescending} from "react-icons/hi";
import {HiOutlineSparkles} from "react-icons/hi";
import {HiOutlineSpeakerphone} from "react-icons/hi";
import {HiOutlineStar} from "react-icons/hi";
import {HiOutlineStatusOffline} from "react-icons/hi";
import {HiOutlineStatusOnline} from "react-icons/hi";
import {HiOutlineStop} from "react-icons/hi";
import {HiOutlineSun} from "react-icons/hi";
import {HiOutlineSupport} from "react-icons/hi";
import {HiOutlineSwitchHorizontal} from "react-icons/hi";
import {HiOutlineSwitchVertical} from "react-icons/hi";
import {HiOutlineTable} from "react-icons/hi";
import {HiOutlineTag} from "react-icons/hi";
import {HiOutlineTemplate} from "react-icons/hi";
import {HiOutlineTerminal} from "react-icons/hi";
import {HiOutlineThumbDown} from "react-icons/hi";
import {HiOutlineThumbUp} from "react-icons/hi";
import {HiOutlineTicket} from "react-icons/hi";
import {HiOutlineTranslate} from "react-icons/hi";
import {HiOutlineTrash} from "react-icons/hi";
import {HiOutlineTrendingDown} from "react-icons/hi";
import {HiOutlineTrendingUp} from "react-icons/hi";
import {HiOutlineTruck} from "react-icons/hi";
import {HiOutlineUpload} from "react-icons/hi";
import {HiOutlineUserAdd} from "react-icons/hi";
import {HiOutlineUserCircle} from "react-icons/hi";
import {HiOutlineUserGroup} from "react-icons/hi";
import {HiOutlineUserRemove} from "react-icons/hi";
import {HiOutlineUser} from "react-icons/hi";
import {HiOutlineUsers} from "react-icons/hi";
import {HiOutlineVariable} from "react-icons/hi";
import {HiOutlineVideoCamera} from "react-icons/hi";
import {HiOutlineViewBoards} from "react-icons/hi";
import {HiOutlineViewGridAdd} from "react-icons/hi";
import {HiOutlineViewGrid} from "react-icons/hi";
import {HiOutlineViewList} from "react-icons/hi";
import {HiOutlineVolumeOff} from "react-icons/hi";
import {HiOutlineVolumeUp} from "react-icons/hi";
import {HiOutlineWifi} from "react-icons/hi";
import {HiOutlineXCircle} from "react-icons/hi";
import {HiOutlineX} from "react-icons/hi";
import {HiOutlineZoomIn} from "react-icons/hi";
import {HiOutlineZoomOut} from "react-icons/hi";




export function nameToReactIconHi(iconName: string): IconType | undefined{
    

    if (iconName === "HiAcademicCap") return HiAcademicCap;
    if (iconName === "HiAdjustments") return HiAdjustments;
    if (iconName === "HiAnnotation") return HiAnnotation;
    if (iconName === "HiArchive") return HiArchive;
    if (iconName === "HiArrowCircleDown") return HiArrowCircleDown;
    if (iconName === "HiArrowCircleLeft") return HiArrowCircleLeft;
    if (iconName === "HiArrowCircleRight") return HiArrowCircleRight;
    if (iconName === "HiArrowCircleUp") return HiArrowCircleUp;
    if (iconName === "HiArrowDown") return HiArrowDown;
    if (iconName === "HiArrowLeft") return HiArrowLeft;
    if (iconName === "HiArrowNarrowDown") return HiArrowNarrowDown;
    if (iconName === "HiArrowNarrowLeft") return HiArrowNarrowLeft;
    if (iconName === "HiArrowNarrowRight") return HiArrowNarrowRight;
    if (iconName === "HiArrowNarrowUp") return HiArrowNarrowUp;
    if (iconName === "HiArrowRight") return HiArrowRight;
    if (iconName === "HiArrowSmDown") return HiArrowSmDown;
    if (iconName === "HiArrowSmLeft") return HiArrowSmLeft;
    if (iconName === "HiArrowSmRight") return HiArrowSmRight;
    if (iconName === "HiArrowSmUp") return HiArrowSmUp;
    if (iconName === "HiArrowUp") return HiArrowUp;
    if (iconName === "HiArrowsExpand") return HiArrowsExpand;
    if (iconName === "HiAtSymbol") return HiAtSymbol;
    if (iconName === "HiBackspace") return HiBackspace;
    if (iconName === "HiBadgeCheck") return HiBadgeCheck;
    if (iconName === "HiBan") return HiBan;
    if (iconName === "HiBeaker") return HiBeaker;
    if (iconName === "HiBell") return HiBell;
    if (iconName === "HiBookOpen") return HiBookOpen;
    if (iconName === "HiBookmarkAlt") return HiBookmarkAlt;
    if (iconName === "HiBookmark") return HiBookmark;
    if (iconName === "HiBriefcase") return HiBriefcase;
    if (iconName === "HiCake") return HiCake;
    if (iconName === "HiCalculator") return HiCalculator;
    if (iconName === "HiCalendar") return HiCalendar;
    if (iconName === "HiCamera") return HiCamera;
    if (iconName === "HiCash") return HiCash;
    if (iconName === "HiChartBar") return HiChartBar;
    if (iconName === "HiChartPie") return HiChartPie;
    if (iconName === "HiChartSquareBar") return HiChartSquareBar;
    if (iconName === "HiChatAlt2") return HiChatAlt2;
    if (iconName === "HiChatAlt") return HiChatAlt;
    if (iconName === "HiChat") return HiChat;
    if (iconName === "HiCheckCircle") return HiCheckCircle;
    if (iconName === "HiCheck") return HiCheck;
    if (iconName === "HiChevronDoubleDown") return HiChevronDoubleDown;
    if (iconName === "HiChevronDoubleLeft") return HiChevronDoubleLeft;
    if (iconName === "HiChevronDoubleRight") return HiChevronDoubleRight;
    if (iconName === "HiChevronDoubleUp") return HiChevronDoubleUp;
    if (iconName === "HiChevronDown") return HiChevronDown;
    if (iconName === "HiChevronLeft") return HiChevronLeft;
    if (iconName === "HiChevronRight") return HiChevronRight;
    if (iconName === "HiChevronUp") return HiChevronUp;
    if (iconName === "HiChip") return HiChip;
    if (iconName === "HiClipboardCheck") return HiClipboardCheck;
    if (iconName === "HiClipboardCopy") return HiClipboardCopy;
    if (iconName === "HiClipboardList") return HiClipboardList;
    if (iconName === "HiClipboard") return HiClipboard;
    if (iconName === "HiClock") return HiClock;
    if (iconName === "HiCloudDownload") return HiCloudDownload;
    if (iconName === "HiCloudUpload") return HiCloudUpload;
    if (iconName === "HiCloud") return HiCloud;
    if (iconName === "HiCode") return HiCode;
    if (iconName === "HiCog") return HiCog;
    if (iconName === "HiCollection") return HiCollection;
    if (iconName === "HiColorSwatch") return HiColorSwatch;
    if (iconName === "HiCreditCard") return HiCreditCard;
    if (iconName === "HiCubeTransparent") return HiCubeTransparent;
    if (iconName === "HiCube") return HiCube;
    if (iconName === "HiCurrencyBangladeshi") return HiCurrencyBangladeshi;
    if (iconName === "HiCurrencyDollar") return HiCurrencyDollar;
    if (iconName === "HiCurrencyEuro") return HiCurrencyEuro;
    if (iconName === "HiCurrencyPound") return HiCurrencyPound;
    if (iconName === "HiCurrencyRupee") return HiCurrencyRupee;
    if (iconName === "HiCurrencyYen") return HiCurrencyYen;
    if (iconName === "HiCursorClick") return HiCursorClick;
    if (iconName === "HiDatabase") return HiDatabase;
    if (iconName === "HiDesktopComputer") return HiDesktopComputer;
    if (iconName === "HiDeviceMobile") return HiDeviceMobile;
    if (iconName === "HiDeviceTablet") return HiDeviceTablet;
    if (iconName === "HiDocumentAdd") return HiDocumentAdd;
    if (iconName === "HiDocumentDownload") return HiDocumentDownload;
    if (iconName === "HiDocumentDuplicate") return HiDocumentDuplicate;
    if (iconName === "HiDocumentRemove") return HiDocumentRemove;
    if (iconName === "HiDocumentReport") return HiDocumentReport;
    if (iconName === "HiDocumentSearch") return HiDocumentSearch;
    if (iconName === "HiDocumentText") return HiDocumentText;
    if (iconName === "HiDocument") return HiDocument;
    if (iconName === "HiDotsCircleHorizontal") return HiDotsCircleHorizontal;
    if (iconName === "HiDotsHorizontal") return HiDotsHorizontal;
    if (iconName === "HiDotsVertical") return HiDotsVertical;
    if (iconName === "HiDownload") return HiDownload;
    if (iconName === "HiDuplicate") return HiDuplicate;
    if (iconName === "HiEmojiHappy") return HiEmojiHappy;
    if (iconName === "HiEmojiSad") return HiEmojiSad;
    if (iconName === "HiExclamationCircle") return HiExclamationCircle;
    if (iconName === "HiExclamation") return HiExclamation;
    if (iconName === "HiExternalLink") return HiExternalLink;
    if (iconName === "HiEyeOff") return HiEyeOff;
    if (iconName === "HiEye") return HiEye;
    if (iconName === "HiFastForward") return HiFastForward;
    if (iconName === "HiFilm") return HiFilm;
    if (iconName === "HiFilter") return HiFilter;
    if (iconName === "HiFingerPrint") return HiFingerPrint;
    if (iconName === "HiFire") return HiFire;
    if (iconName === "HiFlag") return HiFlag;
    if (iconName === "HiFolderAdd") return HiFolderAdd;
    if (iconName === "HiFolderDownload") return HiFolderDownload;
    if (iconName === "HiFolderOpen") return HiFolderOpen;
    if (iconName === "HiFolderRemove") return HiFolderRemove;
    if (iconName === "HiFolder") return HiFolder;
    if (iconName === "HiGift") return HiGift;
    if (iconName === "HiGlobeAlt") return HiGlobeAlt;
    if (iconName === "HiGlobe") return HiGlobe;
    if (iconName === "HiHand") return HiHand;
    if (iconName === "HiHashtag") return HiHashtag;
    if (iconName === "HiHeart") return HiHeart;
    if (iconName === "HiHome") return HiHome;
    if (iconName === "HiIdentification") return HiIdentification;
    if (iconName === "HiInboxIn") return HiInboxIn;
    if (iconName === "HiInbox") return HiInbox;
    if (iconName === "HiInformationCircle") return HiInformationCircle;
    if (iconName === "HiKey") return HiKey;
    if (iconName === "HiLibrary") return HiLibrary;
    if (iconName === "HiLightBulb") return HiLightBulb;
    if (iconName === "HiLightningBolt") return HiLightningBolt;
    if (iconName === "HiLink") return HiLink;
    if (iconName === "HiLocationMarker") return HiLocationMarker;
    if (iconName === "HiLockClosed") return HiLockClosed;
    if (iconName === "HiLockOpen") return HiLockOpen;
    if (iconName === "HiLogin") return HiLogin;
    if (iconName === "HiLogout") return HiLogout;
    if (iconName === "HiMailOpen") return HiMailOpen;
    if (iconName === "HiMail") return HiMail;
    if (iconName === "HiMap") return HiMap;
    if (iconName === "HiMenuAlt1") return HiMenuAlt1;
    if (iconName === "HiMenuAlt2") return HiMenuAlt2;
    if (iconName === "HiMenuAlt3") return HiMenuAlt3;
    if (iconName === "HiMenuAlt4") return HiMenuAlt4;
    if (iconName === "HiMenu") return HiMenu;
    if (iconName === "HiMicrophone") return HiMicrophone;
    if (iconName === "HiMinusCircle") return HiMinusCircle;
    if (iconName === "HiMinusSm") return HiMinusSm;
    if (iconName === "HiMinus") return HiMinus;
    if (iconName === "HiMoon") return HiMoon;
    if (iconName === "HiMusicNote") return HiMusicNote;
    if (iconName === "HiNewspaper") return HiNewspaper;
    if (iconName === "HiOfficeBuilding") return HiOfficeBuilding;
    if (iconName === "HiPaperAirplane") return HiPaperAirplane;
    if (iconName === "HiPaperClip") return HiPaperClip;
    if (iconName === "HiPause") return HiPause;
    if (iconName === "HiPencilAlt") return HiPencilAlt;
    if (iconName === "HiPencil") return HiPencil;
    if (iconName === "HiPhoneIncoming") return HiPhoneIncoming;
    if (iconName === "HiPhoneMissedCall") return HiPhoneMissedCall;
    if (iconName === "HiPhoneOutgoing") return HiPhoneOutgoing;
    if (iconName === "HiPhone") return HiPhone;
    if (iconName === "HiPhotograph") return HiPhotograph;
    if (iconName === "HiPlay") return HiPlay;
    if (iconName === "HiPlusCircle") return HiPlusCircle;
    if (iconName === "HiPlusSm") return HiPlusSm;
    if (iconName === "HiPlus") return HiPlus;
    if (iconName === "HiPresentationChartBar") return HiPresentationChartBar;
    if (iconName === "HiPresentationChartLine") return HiPresentationChartLine;
    if (iconName === "HiPrinter") return HiPrinter;
    if (iconName === "HiPuzzle") return HiPuzzle;
    if (iconName === "HiQrcode") return HiQrcode;
    if (iconName === "HiQuestionMarkCircle") return HiQuestionMarkCircle;
    if (iconName === "HiReceiptRefund") return HiReceiptRefund;
    if (iconName === "HiReceiptTax") return HiReceiptTax;
    if (iconName === "HiRefresh") return HiRefresh;
    if (iconName === "HiReply") return HiReply;
    if (iconName === "HiRewind") return HiRewind;
    if (iconName === "HiRss") return HiRss;
    if (iconName === "HiSaveAs") return HiSaveAs;
    if (iconName === "HiSave") return HiSave;
    if (iconName === "HiScale") return HiScale;
    if (iconName === "HiScissors") return HiScissors;
    if (iconName === "HiSearchCircle") return HiSearchCircle;
    if (iconName === "HiSearch") return HiSearch;
    if (iconName === "HiSelector") return HiSelector;
    if (iconName === "HiServer") return HiServer;
    if (iconName === "HiShare") return HiShare;
    if (iconName === "HiShieldCheck") return HiShieldCheck;
    if (iconName === "HiShieldExclamation") return HiShieldExclamation;
    if (iconName === "HiShoppingBag") return HiShoppingBag;
    if (iconName === "HiShoppingCart") return HiShoppingCart;
    if (iconName === "HiSortAscending") return HiSortAscending;
    if (iconName === "HiSortDescending") return HiSortDescending;
    if (iconName === "HiSparkles") return HiSparkles;
    if (iconName === "HiSpeakerphone") return HiSpeakerphone;
    if (iconName === "HiStar") return HiStar;
    if (iconName === "HiStatusOffline") return HiStatusOffline;
    if (iconName === "HiStatusOnline") return HiStatusOnline;
    if (iconName === "HiStop") return HiStop;
    if (iconName === "HiSun") return HiSun;
    if (iconName === "HiSupport") return HiSupport;
    if (iconName === "HiSwitchHorizontal") return HiSwitchHorizontal;
    if (iconName === "HiSwitchVertical") return HiSwitchVertical;
    if (iconName === "HiTable") return HiTable;
    if (iconName === "HiTag") return HiTag;
    if (iconName === "HiTemplate") return HiTemplate;
    if (iconName === "HiTerminal") return HiTerminal;
    if (iconName === "HiThumbDown") return HiThumbDown;
    if (iconName === "HiThumbUp") return HiThumbUp;
    if (iconName === "HiTicket") return HiTicket;
    if (iconName === "HiTranslate") return HiTranslate;
    if (iconName === "HiTrash") return HiTrash;
    if (iconName === "HiTrendingDown") return HiTrendingDown;
    if (iconName === "HiTrendingUp") return HiTrendingUp;
    if (iconName === "HiTruck") return HiTruck;
    if (iconName === "HiUpload") return HiUpload;
    if (iconName === "HiUserAdd") return HiUserAdd;
    if (iconName === "HiUserCircle") return HiUserCircle;
    if (iconName === "HiUserGroup") return HiUserGroup;
    if (iconName === "HiUserRemove") return HiUserRemove;
    if (iconName === "HiUser") return HiUser;
    if (iconName === "HiUsers") return HiUsers;
    if (iconName === "HiVariable") return HiVariable;
    if (iconName === "HiVideoCamera") return HiVideoCamera;
    if (iconName === "HiViewBoards") return HiViewBoards;
    if (iconName === "HiViewGridAdd") return HiViewGridAdd;
    if (iconName === "HiViewGrid") return HiViewGrid;
    if (iconName === "HiViewList") return HiViewList;
    if (iconName === "HiVolumeOff") return HiVolumeOff;
    if (iconName === "HiVolumeUp") return HiVolumeUp;
    if (iconName === "HiWifi") return HiWifi;
    if (iconName === "HiXCircle") return HiXCircle;
    if (iconName === "HiX") return HiX;
    if (iconName === "HiZoomIn") return HiZoomIn;
    if (iconName === "HiZoomOut") return HiZoomOut;
    if (iconName === "HiOutlineAcademicCap") return HiOutlineAcademicCap;
    if (iconName === "HiOutlineAdjustments") return HiOutlineAdjustments;
    if (iconName === "HiOutlineAnnotation") return HiOutlineAnnotation;
    if (iconName === "HiOutlineArchive") return HiOutlineArchive;
    if (iconName === "HiOutlineArrowCircleDown") return HiOutlineArrowCircleDown;
    if (iconName === "HiOutlineArrowCircleLeft") return HiOutlineArrowCircleLeft;
    if (iconName === "HiOutlineArrowCircleRight") return HiOutlineArrowCircleRight;
    if (iconName === "HiOutlineArrowCircleUp") return HiOutlineArrowCircleUp;
    if (iconName === "HiOutlineArrowDown") return HiOutlineArrowDown;
    if (iconName === "HiOutlineArrowLeft") return HiOutlineArrowLeft;
    if (iconName === "HiOutlineArrowNarrowDown") return HiOutlineArrowNarrowDown;
    if (iconName === "HiOutlineArrowNarrowLeft") return HiOutlineArrowNarrowLeft;
    if (iconName === "HiOutlineArrowNarrowRight") return HiOutlineArrowNarrowRight;
    if (iconName === "HiOutlineArrowNarrowUp") return HiOutlineArrowNarrowUp;
    if (iconName === "HiOutlineArrowRight") return HiOutlineArrowRight;
    if (iconName === "HiOutlineArrowSmDown") return HiOutlineArrowSmDown;
    if (iconName === "HiOutlineArrowSmLeft") return HiOutlineArrowSmLeft;
    if (iconName === "HiOutlineArrowSmRight") return HiOutlineArrowSmRight;
    if (iconName === "HiOutlineArrowSmUp") return HiOutlineArrowSmUp;
    if (iconName === "HiOutlineArrowUp") return HiOutlineArrowUp;
    if (iconName === "HiOutlineArrowsExpand") return HiOutlineArrowsExpand;
    if (iconName === "HiOutlineAtSymbol") return HiOutlineAtSymbol;
    if (iconName === "HiOutlineBackspace") return HiOutlineBackspace;
    if (iconName === "HiOutlineBadgeCheck") return HiOutlineBadgeCheck;
    if (iconName === "HiOutlineBan") return HiOutlineBan;
    if (iconName === "HiOutlineBeaker") return HiOutlineBeaker;
    if (iconName === "HiOutlineBell") return HiOutlineBell;
    if (iconName === "HiOutlineBookOpen") return HiOutlineBookOpen;
    if (iconName === "HiOutlineBookmarkAlt") return HiOutlineBookmarkAlt;
    if (iconName === "HiOutlineBookmark") return HiOutlineBookmark;
    if (iconName === "HiOutlineBriefcase") return HiOutlineBriefcase;
    if (iconName === "HiOutlineCake") return HiOutlineCake;
    if (iconName === "HiOutlineCalculator") return HiOutlineCalculator;
    if (iconName === "HiOutlineCalendar") return HiOutlineCalendar;
    if (iconName === "HiOutlineCamera") return HiOutlineCamera;
    if (iconName === "HiOutlineCash") return HiOutlineCash;
    if (iconName === "HiOutlineChartBar") return HiOutlineChartBar;
    if (iconName === "HiOutlineChartPie") return HiOutlineChartPie;
    if (iconName === "HiOutlineChartSquareBar") return HiOutlineChartSquareBar;
    if (iconName === "HiOutlineChatAlt2") return HiOutlineChatAlt2;
    if (iconName === "HiOutlineChatAlt") return HiOutlineChatAlt;
    if (iconName === "HiOutlineChat") return HiOutlineChat;
    if (iconName === "HiOutlineCheckCircle") return HiOutlineCheckCircle;
    if (iconName === "HiOutlineCheck") return HiOutlineCheck;
    if (iconName === "HiOutlineChevronDoubleDown") return HiOutlineChevronDoubleDown;
    if (iconName === "HiOutlineChevronDoubleLeft") return HiOutlineChevronDoubleLeft;
    if (iconName === "HiOutlineChevronDoubleRight") return HiOutlineChevronDoubleRight;
    if (iconName === "HiOutlineChevronDoubleUp") return HiOutlineChevronDoubleUp;
    if (iconName === "HiOutlineChevronDown") return HiOutlineChevronDown;
    if (iconName === "HiOutlineChevronLeft") return HiOutlineChevronLeft;
    if (iconName === "HiOutlineChevronRight") return HiOutlineChevronRight;
    if (iconName === "HiOutlineChevronUp") return HiOutlineChevronUp;
    if (iconName === "HiOutlineChip") return HiOutlineChip;
    if (iconName === "HiOutlineClipboardCheck") return HiOutlineClipboardCheck;
    if (iconName === "HiOutlineClipboardCopy") return HiOutlineClipboardCopy;
    if (iconName === "HiOutlineClipboardList") return HiOutlineClipboardList;
    if (iconName === "HiOutlineClipboard") return HiOutlineClipboard;
    if (iconName === "HiOutlineClock") return HiOutlineClock;
    if (iconName === "HiOutlineCloudDownload") return HiOutlineCloudDownload;
    if (iconName === "HiOutlineCloudUpload") return HiOutlineCloudUpload;
    if (iconName === "HiOutlineCloud") return HiOutlineCloud;
    if (iconName === "HiOutlineCode") return HiOutlineCode;
    if (iconName === "HiOutlineCog") return HiOutlineCog;
    if (iconName === "HiOutlineCollection") return HiOutlineCollection;
    if (iconName === "HiOutlineColorSwatch") return HiOutlineColorSwatch;
    if (iconName === "HiOutlineCreditCard") return HiOutlineCreditCard;
    if (iconName === "HiOutlineCubeTransparent") return HiOutlineCubeTransparent;
    if (iconName === "HiOutlineCube") return HiOutlineCube;
    if (iconName === "HiOutlineCurrencyBangladeshi") return HiOutlineCurrencyBangladeshi;
    if (iconName === "HiOutlineCurrencyDollar") return HiOutlineCurrencyDollar;
    if (iconName === "HiOutlineCurrencyEuro") return HiOutlineCurrencyEuro;
    if (iconName === "HiOutlineCurrencyPound") return HiOutlineCurrencyPound;
    if (iconName === "HiOutlineCurrencyRupee") return HiOutlineCurrencyRupee;
    if (iconName === "HiOutlineCurrencyYen") return HiOutlineCurrencyYen;
    if (iconName === "HiOutlineCursorClick") return HiOutlineCursorClick;
    if (iconName === "HiOutlineDatabase") return HiOutlineDatabase;
    if (iconName === "HiOutlineDesktopComputer") return HiOutlineDesktopComputer;
    if (iconName === "HiOutlineDeviceMobile") return HiOutlineDeviceMobile;
    if (iconName === "HiOutlineDeviceTablet") return HiOutlineDeviceTablet;
    if (iconName === "HiOutlineDocumentAdd") return HiOutlineDocumentAdd;
    if (iconName === "HiOutlineDocumentDownload") return HiOutlineDocumentDownload;
    if (iconName === "HiOutlineDocumentDuplicate") return HiOutlineDocumentDuplicate;
    if (iconName === "HiOutlineDocumentRemove") return HiOutlineDocumentRemove;
    if (iconName === "HiOutlineDocumentReport") return HiOutlineDocumentReport;
    if (iconName === "HiOutlineDocumentSearch") return HiOutlineDocumentSearch;
    if (iconName === "HiOutlineDocumentText") return HiOutlineDocumentText;
    if (iconName === "HiOutlineDocument") return HiOutlineDocument;
    if (iconName === "HiOutlineDotsCircleHorizontal") return HiOutlineDotsCircleHorizontal;
    if (iconName === "HiOutlineDotsHorizontal") return HiOutlineDotsHorizontal;
    if (iconName === "HiOutlineDotsVertical") return HiOutlineDotsVertical;
    if (iconName === "HiOutlineDownload") return HiOutlineDownload;
    if (iconName === "HiOutlineDuplicate") return HiOutlineDuplicate;
    if (iconName === "HiOutlineEmojiHappy") return HiOutlineEmojiHappy;
    if (iconName === "HiOutlineEmojiSad") return HiOutlineEmojiSad;
    if (iconName === "HiOutlineExclamationCircle") return HiOutlineExclamationCircle;
    if (iconName === "HiOutlineExclamation") return HiOutlineExclamation;
    if (iconName === "HiOutlineExternalLink") return HiOutlineExternalLink;
    if (iconName === "HiOutlineEyeOff") return HiOutlineEyeOff;
    if (iconName === "HiOutlineEye") return HiOutlineEye;
    if (iconName === "HiOutlineFastForward") return HiOutlineFastForward;
    if (iconName === "HiOutlineFilm") return HiOutlineFilm;
    if (iconName === "HiOutlineFilter") return HiOutlineFilter;
    if (iconName === "HiOutlineFingerPrint") return HiOutlineFingerPrint;
    if (iconName === "HiOutlineFire") return HiOutlineFire;
    if (iconName === "HiOutlineFlag") return HiOutlineFlag;
    if (iconName === "HiOutlineFolderAdd") return HiOutlineFolderAdd;
    if (iconName === "HiOutlineFolderDownload") return HiOutlineFolderDownload;
    if (iconName === "HiOutlineFolderOpen") return HiOutlineFolderOpen;
    if (iconName === "HiOutlineFolderRemove") return HiOutlineFolderRemove;
    if (iconName === "HiOutlineFolder") return HiOutlineFolder;
    if (iconName === "HiOutlineGift") return HiOutlineGift;
    if (iconName === "HiOutlineGlobeAlt") return HiOutlineGlobeAlt;
    if (iconName === "HiOutlineGlobe") return HiOutlineGlobe;
    if (iconName === "HiOutlineHand") return HiOutlineHand;
    if (iconName === "HiOutlineHashtag") return HiOutlineHashtag;
    if (iconName === "HiOutlineHeart") return HiOutlineHeart;
    if (iconName === "HiOutlineHome") return HiOutlineHome;
    if (iconName === "HiOutlineIdentification") return HiOutlineIdentification;
    if (iconName === "HiOutlineInboxIn") return HiOutlineInboxIn;
    if (iconName === "HiOutlineInbox") return HiOutlineInbox;
    if (iconName === "HiOutlineInformationCircle") return HiOutlineInformationCircle;
    if (iconName === "HiOutlineKey") return HiOutlineKey;
    if (iconName === "HiOutlineLibrary") return HiOutlineLibrary;
    if (iconName === "HiOutlineLightBulb") return HiOutlineLightBulb;
    if (iconName === "HiOutlineLightningBolt") return HiOutlineLightningBolt;
    if (iconName === "HiOutlineLink") return HiOutlineLink;
    if (iconName === "HiOutlineLocationMarker") return HiOutlineLocationMarker;
    if (iconName === "HiOutlineLockClosed") return HiOutlineLockClosed;
    if (iconName === "HiOutlineLockOpen") return HiOutlineLockOpen;
    if (iconName === "HiOutlineLogin") return HiOutlineLogin;
    if (iconName === "HiOutlineLogout") return HiOutlineLogout;
    if (iconName === "HiOutlineMailOpen") return HiOutlineMailOpen;
    if (iconName === "HiOutlineMail") return HiOutlineMail;
    if (iconName === "HiOutlineMap") return HiOutlineMap;
    if (iconName === "HiOutlineMenuAlt1") return HiOutlineMenuAlt1;
    if (iconName === "HiOutlineMenuAlt2") return HiOutlineMenuAlt2;
    if (iconName === "HiOutlineMenuAlt3") return HiOutlineMenuAlt3;
    if (iconName === "HiOutlineMenuAlt4") return HiOutlineMenuAlt4;
    if (iconName === "HiOutlineMenu") return HiOutlineMenu;
    if (iconName === "HiOutlineMicrophone") return HiOutlineMicrophone;
    if (iconName === "HiOutlineMinusCircle") return HiOutlineMinusCircle;
    if (iconName === "HiOutlineMinusSm") return HiOutlineMinusSm;
    if (iconName === "HiOutlineMinus") return HiOutlineMinus;
    if (iconName === "HiOutlineMoon") return HiOutlineMoon;
    if (iconName === "HiOutlineMusicNote") return HiOutlineMusicNote;
    if (iconName === "HiOutlineNewspaper") return HiOutlineNewspaper;
    if (iconName === "HiOutlineOfficeBuilding") return HiOutlineOfficeBuilding;
    if (iconName === "HiOutlinePaperAirplane") return HiOutlinePaperAirplane;
    if (iconName === "HiOutlinePaperClip") return HiOutlinePaperClip;
    if (iconName === "HiOutlinePause") return HiOutlinePause;
    if (iconName === "HiOutlinePencilAlt") return HiOutlinePencilAlt;
    if (iconName === "HiOutlinePencil") return HiOutlinePencil;
    if (iconName === "HiOutlinePhoneIncoming") return HiOutlinePhoneIncoming;
    if (iconName === "HiOutlinePhoneMissedCall") return HiOutlinePhoneMissedCall;
    if (iconName === "HiOutlinePhoneOutgoing") return HiOutlinePhoneOutgoing;
    if (iconName === "HiOutlinePhone") return HiOutlinePhone;
    if (iconName === "HiOutlinePhotograph") return HiOutlinePhotograph;
    if (iconName === "HiOutlinePlay") return HiOutlinePlay;
    if (iconName === "HiOutlinePlusCircle") return HiOutlinePlusCircle;
    if (iconName === "HiOutlinePlusSm") return HiOutlinePlusSm;
    if (iconName === "HiOutlinePlus") return HiOutlinePlus;
    if (iconName === "HiOutlinePresentationChartBar") return HiOutlinePresentationChartBar;
    if (iconName === "HiOutlinePresentationChartLine") return HiOutlinePresentationChartLine;
    if (iconName === "HiOutlinePrinter") return HiOutlinePrinter;
    if (iconName === "HiOutlinePuzzle") return HiOutlinePuzzle;
    if (iconName === "HiOutlineQrcode") return HiOutlineQrcode;
    if (iconName === "HiOutlineQuestionMarkCircle") return HiOutlineQuestionMarkCircle;
    if (iconName === "HiOutlineReceiptRefund") return HiOutlineReceiptRefund;
    if (iconName === "HiOutlineReceiptTax") return HiOutlineReceiptTax;
    if (iconName === "HiOutlineRefresh") return HiOutlineRefresh;
    if (iconName === "HiOutlineReply") return HiOutlineReply;
    if (iconName === "HiOutlineRewind") return HiOutlineRewind;
    if (iconName === "HiOutlineRss") return HiOutlineRss;
    if (iconName === "HiOutlineSaveAs") return HiOutlineSaveAs;
    if (iconName === "HiOutlineSave") return HiOutlineSave;
    if (iconName === "HiOutlineScale") return HiOutlineScale;
    if (iconName === "HiOutlineScissors") return HiOutlineScissors;
    if (iconName === "HiOutlineSearchCircle") return HiOutlineSearchCircle;
    if (iconName === "HiOutlineSearch") return HiOutlineSearch;
    if (iconName === "HiOutlineSelector") return HiOutlineSelector;
    if (iconName === "HiOutlineServer") return HiOutlineServer;
    if (iconName === "HiOutlineShare") return HiOutlineShare;
    if (iconName === "HiOutlineShieldCheck") return HiOutlineShieldCheck;
    if (iconName === "HiOutlineShieldExclamation") return HiOutlineShieldExclamation;
    if (iconName === "HiOutlineShoppingBag") return HiOutlineShoppingBag;
    if (iconName === "HiOutlineShoppingCart") return HiOutlineShoppingCart;
    if (iconName === "HiOutlineSortAscending") return HiOutlineSortAscending;
    if (iconName === "HiOutlineSortDescending") return HiOutlineSortDescending;
    if (iconName === "HiOutlineSparkles") return HiOutlineSparkles;
    if (iconName === "HiOutlineSpeakerphone") return HiOutlineSpeakerphone;
    if (iconName === "HiOutlineStar") return HiOutlineStar;
    if (iconName === "HiOutlineStatusOffline") return HiOutlineStatusOffline;
    if (iconName === "HiOutlineStatusOnline") return HiOutlineStatusOnline;
    if (iconName === "HiOutlineStop") return HiOutlineStop;
    if (iconName === "HiOutlineSun") return HiOutlineSun;
    if (iconName === "HiOutlineSupport") return HiOutlineSupport;
    if (iconName === "HiOutlineSwitchHorizontal") return HiOutlineSwitchHorizontal;
    if (iconName === "HiOutlineSwitchVertical") return HiOutlineSwitchVertical;
    if (iconName === "HiOutlineTable") return HiOutlineTable;
    if (iconName === "HiOutlineTag") return HiOutlineTag;
    if (iconName === "HiOutlineTemplate") return HiOutlineTemplate;
    if (iconName === "HiOutlineTerminal") return HiOutlineTerminal;
    if (iconName === "HiOutlineThumbDown") return HiOutlineThumbDown;
    if (iconName === "HiOutlineThumbUp") return HiOutlineThumbUp;
    if (iconName === "HiOutlineTicket") return HiOutlineTicket;
    if (iconName === "HiOutlineTranslate") return HiOutlineTranslate;
    if (iconName === "HiOutlineTrash") return HiOutlineTrash;
    if (iconName === "HiOutlineTrendingDown") return HiOutlineTrendingDown;
    if (iconName === "HiOutlineTrendingUp") return HiOutlineTrendingUp;
    if (iconName === "HiOutlineTruck") return HiOutlineTruck;
    if (iconName === "HiOutlineUpload") return HiOutlineUpload;
    if (iconName === "HiOutlineUserAdd") return HiOutlineUserAdd;
    if (iconName === "HiOutlineUserCircle") return HiOutlineUserCircle;
    if (iconName === "HiOutlineUserGroup") return HiOutlineUserGroup;
    if (iconName === "HiOutlineUserRemove") return HiOutlineUserRemove;
    if (iconName === "HiOutlineUser") return HiOutlineUser;
    if (iconName === "HiOutlineUsers") return HiOutlineUsers;
    if (iconName === "HiOutlineVariable") return HiOutlineVariable;
    if (iconName === "HiOutlineVideoCamera") return HiOutlineVideoCamera;
    if (iconName === "HiOutlineViewBoards") return HiOutlineViewBoards;
    if (iconName === "HiOutlineViewGridAdd") return HiOutlineViewGridAdd;
    if (iconName === "HiOutlineViewGrid") return HiOutlineViewGrid;
    if (iconName === "HiOutlineViewList") return HiOutlineViewList;
    if (iconName === "HiOutlineVolumeOff") return HiOutlineVolumeOff;
    if (iconName === "HiOutlineVolumeUp") return HiOutlineVolumeUp;
    if (iconName === "HiOutlineWifi") return HiOutlineWifi;
    if (iconName === "HiOutlineXCircle") return HiOutlineXCircle;
    if (iconName === "HiOutlineX") return HiOutlineX;
    if (iconName === "HiOutlineZoomIn") return HiOutlineZoomIn;
    if (iconName === "HiOutlineZoomOut") return HiOutlineZoomOut;


    return undefined;
    
    
    
}

